import { mkdtemp, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { createSnapshotManifest, diffRegistries, promoteRegistryCandidate, registryQualityMetrics, rollbackRegistry, runRegistryQualityGate, sha256, writeRegistryCandidate, type AIModel, type CanonicalRegistrySnapshot } from "../src/index.js";
const model = (id: string, overrides: Partial<AIModel> = {}): AIModel => ({ id, provider: "test", providerModelId: id, capabilities: { streaming: "supported", vision: "unknown", tools: "supported", reasoning: "unknown", structuredOutput: "supported", audioInput: "unknown", audioOutput: "unknown", embeddings: "unknown" }, limits: { contextWindow: 1000 }, pricing: { currency: "USD", inputPerMillionTokens: 1, pricingSource: "test" }, routes: [{ id: `test/${id}`, provider: "test", providerModelId: id }], provenance: { source: "test", sourceModelId: id, fetchedAt: "2026-01-01T00:00:00Z", verifiedAt: "2026-01-01T00:00:00Z", normalizationVersion: "1", adapterVersion: "test@1", capabilityEvidence: [] }, quality: { completeness: 1, confidence: 1, warnings: [] }, facts: { "limits.contextWindow": { value: 1000, confidence: 1, evidence: [{ id: `${id}:context`, modelId: id, field: "limits.contextWindow", value: 1000, source: "test", kind: "official_api", tier: 1, observedAt: "2026-01-01T00:00:00Z", confidence: 1 }], verifiedAt: "2026-01-01T00:00:00Z", status: "unverified", conflicts: [] } }, ...overrides });
const snapshot = (version: string, count: number): CanonicalRegistrySnapshot => ({ version, generatedAt: "2026-01-01T00:00:00Z", models: Array.from({ length: count }, (_, i) => model(`m${i}`)), sourceVersions: { test: "2026-01-01T00:00:00Z" }, rawRecords: [] });
describe("production registry pipeline", () => {
  it("passes normal growth and fails model, route, pricing, context, and capability collapse", () => {
    const base = snapshot("1.0.0", 10); expect(runRegistryQualityGate(base, snapshot("1.0.1", 11)).status).toBe("pass");
    expect(runRegistryQualityGate(base, snapshot("1.0.1", 2)).violations.some((item) => item.code === "MODEL_COLLAPSE")).toBe(true);
    const noRoutes = snapshot("1.0.1", 10); noRoutes.models.forEach((item) => item.routes = []); expect(runRegistryQualityGate(base, noRoutes).violations.some((item) => item.code === "ROUTE_COLLAPSE")).toBe(true);
    const noPricing = snapshot("1.0.1", 10); noPricing.models.forEach((item) => item.pricing = undefined); expect(runRegistryQualityGate(base, noPricing).violations.some((item) => item.code === "PRICING_COMPLETENESS_COLLAPSE")).toBe(true);
    const noContext = snapshot("1.0.1", 10); noContext.models.forEach((item) => item.limits = {}); expect(runRegistryQualityGate(base, noContext).violations.some((item) => item.code === "CONTEXT_COMPLETENESS_COLLAPSE")).toBe(true);
    const noTools = snapshot("1.0.1", 10); noTools.models.forEach((item) => item.capabilities.tools = "unknown"); expect(runRegistryQualityGate(base, noTools).violations.some((item) => item.code === "CAPABILITY_DATA_COLLAPSE")).toBe(true);
  });
  it("creates deterministic manifests and detailed diffs", () => { const a = snapshot("1.0.0", 1), b = snapshot("1.0.1", 2); b.models[0].facts["limits.contextWindow"].value = 2000; expect(createSnapshotManifest(a)).toEqual(createSnapshotManifest(a)); const diff = diffRegistries(a, b); expect(diff.models.added).toEqual(["m1"]); expect(diff.facts[0]).toMatchObject({ modelId: "m0", fact: "limits.contextWindow", previous: 1000, current: 2000 }); });
  it("keeps current untouched until promotion and supports verified rollback", async () => { const dir = await mkdtemp(join(tmpdir(), "registry-pipeline-")), first = snapshot("1.0.0", 1); await writeRegistryCandidate(dir, first); await promoteRegistryCandidate(dir); const current = await readFile(join(dir, "current.json"), "utf8"); const second = snapshot("1.0.1", 2); await writeRegistryCandidate(dir, second); expect(await readFile(join(dir, "current.json"), "utf8")).toBe(current); await promoteRegistryCandidate(dir); await rollbackRegistry(dir, "1.0.0"); expect(JSON.parse(await readFile(join(dir, "current.json"), "utf8")).version).toBe("1.0.0"); expect(JSON.parse(await readFile(join(dir, "1.0.1.json"), "utf8")).version).toBe("1.0.1"); });
  it("detects checksum corruption", async () => { const manifest = createSnapshotManifest(snapshot("1.0.0", 1)); expect(manifest.checksums.registry).toHaveLength(64); expect(sha256("different")).not.toBe(manifest.checksums.registry); });
});
