import { describe, expect, it } from "vitest";
import { IntelligentRouter, createRoutingObservation } from "../src/index.js";
import type { AIModel, EvidenceAuthority, EvidenceMethod } from "../../registry/src/index.js";
const model = (id: string, options: { vision?: "supported" | "unsupported" | "unknown"; confidence?: number; authority?: EvidenceAuthority; method?: EvidenceMethod; observedAt?: string; cost?: number; health?: string; provider?: string; local?: boolean; conflicts?: number } = {}): AIModel => {
  const provider = options.provider ?? "openrouter", evidence = { id: `${id}:vision`, source: provider, fact: "capabilities.vision", sourceField: "vision", value: options.vision ?? "supported", method: options.method ?? "provider_declared", authority: options.authority ?? "official_provider", confidence: options.confidence ?? .9, observedAt: options.observedAt ?? "2026-08-13T00:00:00Z" };
  return { id, provider: id.split("/")[0], providerModelId: id, capabilities: { streaming: "supported", vision: options.vision ?? "supported", tools: "supported", reasoning: "unknown", structuredOutput: "supported", audioInput: "unknown", audioOutput: "unknown", embeddings: "unknown" }, limits: { contextWindow: 1000 }, pricing: options.cost === undefined ? undefined : { currency: "USD", inputPerMillionTokens: options.cost, pricingSource: provider }, availability: { status: "available", local: Boolean(options.local) }, lifecycle: { status: "active" }, routes: [{ id: `${provider}/standard`, provider, providerModelId: id, availability: { status: "available", local: Boolean(options.local) }, metadata: options.health ? { health: { status: options.health } } : undefined }], provenance: { source: provider, sourceModelId: id, fetchedAt: "2026-08-13T00:00:00Z", verifiedAt: "2026-08-13T00:00:00Z", normalizationVersion: "1", adapterVersion: "test", capabilityEvidence: [] }, quality: { completeness: 1, confidence: options.confidence ?? .9, freshness: 1, warnings: [] }, facts: { "capabilities.vision": { value: options.vision ?? "supported", confidence: options.confidence ?? .9, evidence: [], verifiedAt: evidence.observedAt, status: options.conflicts ? "conflicting" : "verified", conflicts: [] } }, intelligence: { evidence: [evidence], conflicts: Array.from({ length: options.conflicts ?? 0 }, () => ({ fact: "capabilities.vision", values: [{ value: "supported", evidenceIds: [evidence.id] }, { value: "unknown", evidenceIds: [evidence.id] }], detectedAt: evidence.observedAt })), quality: { completeness: 1, confidence: options.confidence ?? .9, freshness: 1, warnings: [] }, reconciliationVersion: "1" } };
};
describe("evidence-aware intelligent routing", () => {
  const providers = new Set(["openrouter", "ollama"]);
  it("prefers supported, allows penalized unknown, and rejects unsupported", () => { const decision = new IntelligentRouter([model("a/supported"), model("b/unknown", { vision: "unknown" }), model("c/no", { vision: "unsupported" })], providers, new Date("2026-08-13T01:00:00Z")).route({ mode: "vision" }); expect(decision.selected.model.id).toBe("a/supported"); expect(decision.candidates.find((item) => item.model.id === "b/unknown")?.compatibility).toBe("uncertain"); expect(decision.candidates.find((item) => item.model.id === "c/no")?.score).toBe(0); });
  it("strict mode rejects unknown", () => { expect(() => new IntelligentRouter([model("b/unknown", { vision: "unknown" })], providers).route({ mode: "vision", strictCapabilities: true })).toThrow("No executable"); });
  it("official and runtime-verified evidence beat inference", () => { const inferred = model("a/inferred", { confidence: .9, authority: "inference", method: "adapter_inferred" }), runtime = model("b/runtime", { confidence: .9, authority: "runtime", method: "runtime_verified" }); const result = new IntelligentRouter([inferred, runtime], providers, new Date("2026-08-13T01:00:00Z")).route({ mode: "vision" }); expect(result.selected.model.id).toBe("b/runtime"); });
  it("fresh evidence beats stale and capability facts decay slower than pricing", () => { const fresh = model("a/fresh", { observedAt: "2026-08-13T00:00:00Z" }), stale = model("b/stale", { observedAt: "2024-01-01T00:00:00Z" }); expect(new IntelligentRouter([stale, fresh], providers, new Date("2026-08-13T01:00:00Z")).route({ mode: "vision" }).selected.model.id).toBe("a/fresh"); });
  it("conflicts lower score", () => { const clean = model("a/clean"), conflict = model("b/conflict", { conflicts: 1 }); expect(new IntelligentRouter([conflict, clean], providers, new Date("2026-08-13T01:00:00Z")).route({ mode: "vision" }).selected.model.id).toBe("a/clean"); });
  it("excludes providers without credentials and unavailable routes", () => { const absent = model("a/absent", { provider: "anthropic" }), available = model("b/available"); expect(new IntelligentRouter([absent, available], providers).route({ mode: "vision" }).selected.model.id).toBe("b/available"); });
  it("cheap prefers known cheap and unknown is not free", () => { const unknown = model("a/unknown-price"), priced = model("b/priced", { cost: .1 }); expect(new IntelligentRouter([unknown, priced], providers).route({ mode: "cheap" }).selected.model.id).toBe("b/priced"); });
  it("healthy routes beat degraded routes", () => { const degraded = model("a/degraded", { health: "degraded" }), healthy = model("b/healthy", { health: "healthy" }); expect(new IntelligentRouter([degraded, healthy], providers).route({ mode: "auto" }).selected.model.id).toBe("b/healthy"); });
  it("local intent selects an executable local runtime", () => { const hosted = model("a/hosted"), local = model("b/local", { provider: "ollama", local: true }); expect(new IntelligentRouter([hosted, local], providers).route({ mode: "local" }).selected.model.id).toBe("b/local"); });
  it("is deterministic and produces reasons and fallback", () => { const router = new IntelligentRouter([model("b/model"), model("a/model")], providers, new Date("2026-08-13T00:00:00Z")), one = router.route({ mode: "vision" }), two = router.route({ mode: "vision" }); expect(one.selected.model.id).toBe(two.selected.model.id); expect(one.selected.reasons.length).toBeGreaterThan(0); expect(one.fallback).toHaveLength(1); });
  it("keeps explicit model selection authoritative", () => { const selected = new IntelligentRouter([model("a/high", { confidence: 1 }), model("b/explicit", { confidence: .6 })], providers).route({ explicitModelId: "b/explicit" }); expect(selected.selected.model.id).toBe("b/explicit"); });
  it("supports fast and reasoning policy weights", () => { const reasoning = model("a/reasoning"); reasoning.capabilities.reasoning = "supported"; expect(new IntelligentRouter([reasoning], providers).route({ mode: "reasoning" }).selected.model.id).toBe("a/reasoning"); expect(new IntelligentRouter([reasoning], providers).route({ mode: "fast" }).mode).toBe("fast"); });
  it("emits observations without mutating the registry", () => { const original = model("a/model"), candidate = new IntelligentRouter([original], providers).route().selected, observation = createRoutingObservation(candidate, "request-1", new Error("429 rate limited"), "2026-08-13T00:00:00Z"); expect(observation.event).toBe("rate_limited"); expect(original).toEqual(model("a/model")); });
});
