import { readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createSnapshotManifest, diffRegistries, promoteRegistryCandidate, readSnapshotAndManifest, registryQualityMetrics, rollbackRegistry, runRegistryQualityGate, sha256, validateCanonicalRegistry, type CanonicalRegistrySnapshot } from "../../registry/src/index.js";
const directory = resolve(process.env.REGISTRY_SNAPSHOT_DIR || "registry/snapshots");
const command = process.argv[2];
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
async function snapshot(name: string): Promise<CanonicalRegistrySnapshot> { return JSON.parse(await readFile(resolve(directory, `${name}.json`), "utf8")) as CanonicalRegistrySnapshot; }
const verified = async (name: string) => (await readSnapshotAndManifest(directory, name)).snapshot;
async function capture(): Promise<void> { const current = await verified("current"); await writeFile(resolve(directory, "baseline.json"), json(current)); await writeFile(resolve(directory, "baseline.manifest.json"), json(createSnapshotManifest(current, "current"))); console.log(`Captured baseline ${current.version}`); }
async function validate(): Promise<void> { const name = process.argv.includes("--current") ? "current" : "candidate"; const { snapshot: candidate } = await readSnapshotAndManifest(directory, name); const issues = validateCanonicalRegistry(candidate), errors = issues.filter((item) => item.severity === "error"); if (errors.length) throw new Error(errors.map((item) => `${item.code}: ${item.message}`).join("; ")); console.log(`PASS schema, IDs, values, evidence references, checksum (${candidate.version})`); }
async function quality(): Promise<void> { const baseline = await snapshot("baseline"), candidate = await snapshot("candidate"); const allow = process.argv.includes("--allow-model-count-change"); const reason = process.argv.find((arg) => arg.startsWith("--reason="))?.slice(9); if (allow && !reason) throw new Error("A recorded --reason is required for model-count override"); const result = runRegistryQualityGate(baseline, candidate, undefined, { allowModelCountChange: allow, reason }); await writeFile(resolve(directory, "quality-gate.json"), json(result)); console.log(`Quality gate: ${result.status.toUpperCase()}`); for (const violation of result.violations) console.log(`${violation.code}: ${violation.message}`); if (result.status === "fail") process.exitCode = 1; }
async function diff(): Promise<void> { const baseline = await snapshot("baseline"), candidate = await snapshot("candidate"), result = diffRegistries(baseline, candidate); await writeFile(resolve(directory, "registry-diff.json"), json(result)); console.log(`Models +${result.models.added.length} -${result.models.removed.length} ~${result.models.changed.length}`); console.log(`Routes +${result.routes.added.length} -${result.routes.removed.length} ~${result.routes.changed.length}`); console.log(`Evidence +${result.evidence.added.length} -${result.evidence.removed.length} ~${result.evidence.changed.length}`); console.log(`Facts ${result.facts.length}; conflicts +${result.conflicts.added.length} -${result.conflicts.resolved.length}`); }
async function report(): Promise<void> { const baseline = await snapshot("baseline"), candidate = await snapshot("candidate"), qualityResult = JSON.parse(await readFile(resolve(directory, "quality-gate.json"), "utf8")); const before = registryQualityMetrics(baseline), after = registryQualityMetrics(candidate); const lines = ["## Registry Update", "", "### Summary", `Models: ${before.canonicalModels} → ${after.canonicalModels}`, `Routes: ${before.routes} → ${after.routes}`, `Evidence: ${before.evidence} → ${after.evidence}`, `Conflicts: ${before.conflicts} → ${after.conflicts}`, `Unknown capabilities: ${before.unknownCapabilities} → ${after.unknownCapabilities}`, `Context completeness: ${before.contextCompleteness.toFixed(1)}% → ${after.contextCompleteness.toFixed(1)}%`, `Pricing completeness: ${before.pricingCompleteness.toFixed(1)}% → ${after.pricingCompleteness.toFixed(1)}%`, "", `### Quality Gate\n${qualityResult.status === "pass" ? "✅ PASS" : "❌ FAIL"}`, "", "### Validation\n✅ Schema\n✅ Duplicate IDs\n✅ Context values\n✅ Pricing values\n✅ Evidence references\n✅ Checksums"]; const text = `${lines.join("\n")}\n`; await writeFile(resolve(directory, "registry-report.md"), text); console.log(text); }
async function publish(): Promise<void> { const qualityResult = JSON.parse(await readFile(resolve(directory, "quality-gate.json"), "utf8")); if (qualityResult.status !== "pass") throw new Error("Cannot promote a candidate that failed its quality gate"); console.log(`Published ${await promoteRegistryCandidate(directory)}`); }
async function manifests(): Promise<void> { const files = (await readdir(directory)).filter((file) => /^(?:current|\d+\.\d+\.\d+)\.json$/.test(file)); for (const file of files) { const name = file.slice(0, -5), value = await snapshot(name), manifest = createSnapshotManifest(value, name === "current" ? "current" : "published"); await writeFile(resolve(directory, `${name}.manifest.json`), json(manifest)); } console.log(`Generated ${files.length} verified manifests`); }
switch (command) { case "capture": await capture(); break; case "validate": await validate(); break; case "quality": await quality(); break; case "diff": await diff(); break; case "report": await report(); break; case "publish": await publish(); break; case "manifests": await manifests(); break; case "rollback": { const version = process.argv[3]; if (!version) throw new Error("rollback requires a version"); await rollbackRegistry(directory, version); console.log(`Rolled back to ${version}`); break; } default: throw new Error(`Unknown registry operation '${command}'`); }
